### ISSUE TITLE
various webdriver instances

### ISSUE THREAD

**Issue by steam1** [webdriverextensions/webdriverextensions#115]
Hi,

First of all, thank you for your effort in this library. We have started using this library and have needed several instances of webdriver, such as

https://github.com/barancev/webdriver-factory

I created MyClass which extends from com.github.webdriverextensions.Bot and I have access to the driver () but when I made another instance of MyClass and got the driver by the driver () method, another instance of the Driver loses due to WebDriverExtensionsContext

Any suggestions on how to implement multiple instances of drivers?
Thanks a lot.

**Comment by xinaiz** [comment]
WebDriverExtensionsContext can store 1 driver per thread. If you want more instances, you could create them in different threads.

**Comment by andidev** [comment]
The Bot is implemented with static methods and they get the driver from either the WebElement passed through as method argument or if no WebElement is passed it uses the WebDriver retrieved with [WebDriverExtensionsContext.getDriver()](https://github.com/webdriverextensions/webdriverextensions/blob/master/src/main/java/com/github/webdriverextensions/WebDriverExtensionsContext.java).
Since WebDriverExtensionsContext uses a InheritableThreadLocal I am not sure one could create another thread and set a another driver in the WebDriverExtensionsContext to be used within the new thread. Not sure why WebDriverExtensionsContext is not using a simple ThreadLocal actually, maybe this should be changed.

**Comment by xinaiz** [comment]
Just tested it and have run multiple threads concurrently, calling setDriver() in each thread, and multiple browsers have been opened. Bot functions executed as expected, so it should work fine.Using  multiple browsers of same type works too.

**Comment by andidev** [comment]
Great! I'm closing this then.
