### ISSUE TITLE
Strange Log Message

### ISSUE THREAD

**Issue by dve** [webdriverextensions/webdriverextensions#82]
Running my travis-ci tests i got a strange log message: 
`09:14 37   INFO    Skipping test BotTest.optionIndexTest@Chrome since Test is annotated to ignore browser [@IgnoreFirefox(platform="LINUX")]            WebDriverRunner:260 `

The test should not be skipped for chrome, only for firefox.

[Link to log](https://travis-ci.org/dve/webdriverextensions/builds/204117847#L4279)

**Comment by andidev** [comment]
Actually chrome tests should be skipped since the DISABLED_BROWSERS_PROPERTY_NAME property is set to skip "chrome" in the `.travis.yml` file. Though the disabled 
The easiest fix for this would to change the log message printed in [WebDriverRunner on line 260](https://github.com/webdriverextensions/webdriverextensions/blob/master/src/main/java/com/github/webdriverextensions/junitrunner/WebDriverRunner.java#L260) to something like 
```"Skipping test {} since Test is ignored. ignored browser annotations: {}, ignored browsers by property " + WebDriverProperties.DISABLED_BROWSERS_PROPERTY_NAME + ": {}"```

**Comment by andidev** [comment]
Released in 3.2.0
